# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='\u8bbf\u95eeIP')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='\u8bbf\u95ee\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bbf\u95ee\u8bb0\u5f55',
                'verbose_name_plural': '\u8bbf\u95ee\u8bb0\u5f55',
            },
        ),
    ]
