# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-22 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='detail',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
