# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 18:56
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u535a\u5ba2==\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u5173\u4e8e',
                'verbose_name_plural': '\u5173\u4e8e',
            },
        ),
    ]
