# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 19:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='userabout',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65e5\u671f'),
        ),
    ]
