# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 19:44
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userabout_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userabout',
            name='about',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u5173\u4e8e'),
        ),
    ]
