# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-27 15:27
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20170622_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u535a\u5ba2==\u5185\u5bb9'),
        ),
    ]
