# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_click_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.IntegerField(default=2017, verbose_name='\u5e74\u4efd'),
        ),
    ]
